// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PostService.Infrastructure.PostgreSql;

#nullable disable

namespace PostService.Infrastructure.Migrations
{
    [DbContext(typeof(SqlContext))]
    partial class SqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Received")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("text");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("OutboxMessage");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("OutboxState");
                });

            modelBuilder.Entity("PostService.Domain.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId");
                });

            modelBuilder.Entity("PostService.Domain.Post", b =>
                {
                    b.OwnsOne("PostService.Domain.Content", "Content", b1 =>
                        {
                            b1.Property<Guid>("PostId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("PostId");

                            b1.ToTable("Posts");

                            b1.WithOwner()
                                .HasForeignKey("PostId");

                            b1.OwnsOne("Shared.Events.SharedObjects.ModerationResult", "ModerationResult", b2 =>
                                {
                                    b2.Property<Guid>("ContentPostId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Hate")
                                        .HasColumnType("integer");

                                    b2.Property<int>("SelfHarm")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Sexual")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Violence")
                                        .HasColumnType("integer");

                                    b2.HasKey("ContentPostId");

                                    b2.ToTable("Posts");

                                    b2.WithOwner()
                                        .HasForeignKey("ContentPostId");
                                });

                            b1.Navigation("ModerationResult");
                        });

                    b.OwnsMany("PostService.Domain.Media", "Media", b1 =>
                        {
                            b1.Property<Guid>("PostId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("BlobName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ContainerName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("TranscodedBlobName")
                                .HasColumnType("text");

                            b1.Property<int>("Type")
                                .HasColumnType("integer");

                            b1.HasKey("PostId", "Id");

                            b1.ToTable("Media");

                            b1.WithOwner()
                                .HasForeignKey("PostId");

                            b1.OwnsOne("Shared.Events.SharedObjects.ModerationResult", "ModerationResult", b2 =>
                                {
                                    b2.Property<Guid>("MediaPostId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("MediaId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Hate")
                                        .HasColumnType("integer");

                                    b2.Property<int>("SelfHarm")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Sexual")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Violence")
                                        .HasColumnType("integer");

                                    b2.HasKey("MediaPostId", "MediaId");

                                    b2.ToTable("Media");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaPostId", "MediaId");
                                });

                            b1.OwnsOne("Shared.Events.SharedObjects.MediaInstruction", "Instruction", b2 =>
                                {
                                    b2.Property<Guid>("MediaPostId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("MediaId")
                                        .HasColumnType("integer");

                                    b2.HasKey("MediaPostId", "MediaId");

                                    b2.ToTable("Media");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaPostId", "MediaId");

                                    b2.OwnsOne("Shared.Events.SharedObjects.MetadataInstruction", "MetadataInstruction", b3 =>
                                        {
                                            b3.Property<Guid>("MediaInstructionMediaPostId")
                                                .HasColumnType("uuid");

                                            b3.Property<int>("MediaInstructionMediaId")
                                                .HasColumnType("integer");

                                            b3.Property<double>("Duration")
                                                .HasColumnType("double precision");

                                            b3.HasKey("MediaInstructionMediaPostId", "MediaInstructionMediaId");

                                            b3.ToTable("Media");

                                            b3.WithOwner()
                                                .HasForeignKey("MediaInstructionMediaPostId", "MediaInstructionMediaId");
                                        });

                                    b2.OwnsOne("Shared.Events.SharedObjects.ModerationInstruction", "ModerationInstruction", b3 =>
                                        {
                                            b3.Property<Guid>("MediaInstructionMediaPostId")
                                                .HasColumnType("uuid");

                                            b3.Property<int>("MediaInstructionMediaId")
                                                .HasColumnType("integer");

                                            b3.Property<double>("Fps")
                                                .HasColumnType("double precision");

                                            b3.Property<int?>("MaxHate")
                                                .HasColumnType("integer");

                                            b3.Property<int?>("MaxSelfHarm")
                                                .HasColumnType("integer");

                                            b3.Property<int?>("MaxSexual")
                                                .HasColumnType("integer");

                                            b3.Property<int?>("MaxViolence")
                                                .HasColumnType("integer");

                                            b3.Property<double>("Resolution")
                                                .HasColumnType("double precision");

                                            b3.HasKey("MediaInstructionMediaPostId", "MediaInstructionMediaId");

                                            b3.ToTable("Media");

                                            b3.WithOwner()
                                                .HasForeignKey("MediaInstructionMediaPostId", "MediaInstructionMediaId");
                                        });

                                    b2.OwnsMany("Shared.Events.SharedObjects.ThumbnailInstruction", "ThumbnailInstructions", b3 =>
                                        {
                                            b3.Property<Guid>("MediaInstructionMediaPostId")
                                                .HasColumnType("uuid");

                                            b3.Property<int>("MediaInstructionMediaId")
                                                .HasColumnType("integer");

                                            b3.Property<int>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("integer");

                                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b3.Property<int>("Id"));

                                            b3.Property<bool>("IsSquare")
                                                .HasColumnType("boolean");

                                            b3.Property<double>("Resolution")
                                                .HasColumnType("double precision");

                                            b3.HasKey("MediaInstructionMediaPostId", "MediaInstructionMediaId", "Id");

                                            b3.ToTable("ThumbnailInstruction");

                                            b3.WithOwner()
                                                .HasForeignKey("MediaInstructionMediaPostId", "MediaInstructionMediaId");
                                        });

                                    b2.OwnsOne("Shared.Events.SharedObjects.TranscodingInstruction", "TranscodingInstruction", b3 =>
                                        {
                                            b3.Property<Guid>("MediaInstructionMediaPostId")
                                                .HasColumnType("uuid");

                                            b3.Property<int>("MediaInstructionMediaId")
                                                .HasColumnType("integer");

                                            b3.Property<double>("Resolution")
                                                .HasColumnType("double precision");

                                            b3.HasKey("MediaInstructionMediaPostId", "MediaInstructionMediaId");

                                            b3.ToTable("Media");

                                            b3.WithOwner()
                                                .HasForeignKey("MediaInstructionMediaPostId", "MediaInstructionMediaId");
                                        });

                                    b2.Navigation("MetadataInstruction")
                                        .IsRequired();

                                    b2.Navigation("ModerationInstruction");

                                    b2.Navigation("ThumbnailInstructions");

                                    b2.Navigation("TranscodingInstruction");
                                });

                            b1.OwnsOne("Shared.Events.SharedObjects.Metadata", "Metadata", b2 =>
                                {
                                    b2.Property<Guid>("MediaPostId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("MediaId")
                                        .HasColumnType("integer");

                                    b2.Property<double>("Duration")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Height")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Width")
                                        .HasColumnType("double precision");

                                    b2.HasKey("MediaPostId", "MediaId");

                                    b2.ToTable("Media");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaPostId", "MediaId");
                                });

                            b1.OwnsMany("Shared.Events.SharedObjects.Thumbnail", "Thumbnails", b2 =>
                                {
                                    b2.Property<Guid>("MediaPostId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("MediaId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("BlobName")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<bool>("IsSquare")
                                        .HasColumnType("boolean");

                                    b2.Property<double>("Resolution")
                                        .HasColumnType("double precision");

                                    b2.HasKey("MediaPostId", "MediaId", "Id");

                                    b2.ToTable("Thumbnail");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaPostId", "MediaId");
                                });

                            b1.Navigation("Instruction")
                                .IsRequired();

                            b1.Navigation("Metadata");

                            b1.Navigation("ModerationResult");

                            b1.Navigation("Thumbnails");
                        });

                    b.Navigation("Content");

                    b.Navigation("Media");
                });
#pragma warning restore 612, 618
        }
    }
}
