// <auto-generated />
using System;
using MediaService.Infrastructure.PostgreSql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MediaService.Infrastructure.Migrations
{
    [DbContext(typeof(SqlContext))]
    partial class SqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Received")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("text");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("OutboxMessage");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("OutboxState");
                });

            modelBuilder.Entity("MediaService.Domain.Media", b =>
                {
                    b.Property<string>("ContainerName")
                        .HasColumnType("text");

                    b.Property<string>("BlobName")
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("TranscodedBlobName")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("ContainerName", "BlobName");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId");
                });

            modelBuilder.Entity("MediaService.Domain.Media", b =>
                {
                    b.OwnsOne("Shared.Events.SharedObjects.MediaInstruction", "Instruction", b1 =>
                        {
                            b1.Property<string>("MediaContainerName")
                                .HasColumnType("text");

                            b1.Property<string>("MediaBlobName")
                                .HasColumnType("text");

                            b1.HasKey("MediaContainerName", "MediaBlobName");

                            b1.ToTable("Media");

                            b1.WithOwner()
                                .HasForeignKey("MediaContainerName", "MediaBlobName");

                            b1.OwnsOne("Shared.Events.SharedObjects.MetadataInstruction", "MetadataInstruction", b2 =>
                                {
                                    b2.Property<string>("MediaInstructionMediaContainerName")
                                        .HasColumnType("text");

                                    b2.Property<string>("MediaInstructionMediaBlobName")
                                        .HasColumnType("text");

                                    b2.Property<double>("Duration")
                                        .HasColumnType("double precision");

                                    b2.HasKey("MediaInstructionMediaContainerName", "MediaInstructionMediaBlobName");

                                    b2.ToTable("Media");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaInstructionMediaContainerName", "MediaInstructionMediaBlobName");
                                });

                            b1.OwnsOne("Shared.Events.SharedObjects.ModerationInstruction", "ModerationInstruction", b2 =>
                                {
                                    b2.Property<string>("MediaInstructionMediaContainerName")
                                        .HasColumnType("text");

                                    b2.Property<string>("MediaInstructionMediaBlobName")
                                        .HasColumnType("text");

                                    b2.Property<double>("Fps")
                                        .HasColumnType("double precision");

                                    b2.Property<int?>("MaxHate")
                                        .HasColumnType("integer");

                                    b2.Property<int?>("MaxSelfHarm")
                                        .HasColumnType("integer");

                                    b2.Property<int?>("MaxSexual")
                                        .HasColumnType("integer");

                                    b2.Property<int?>("MaxViolence")
                                        .HasColumnType("integer");

                                    b2.Property<double>("Resolution")
                                        .HasColumnType("double precision");

                                    b2.HasKey("MediaInstructionMediaContainerName", "MediaInstructionMediaBlobName");

                                    b2.ToTable("Media");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaInstructionMediaContainerName", "MediaInstructionMediaBlobName");
                                });

                            b1.OwnsMany("Shared.Events.SharedObjects.ThumbnailInstruction", "ThumbnailInstructions", b2 =>
                                {
                                    b2.Property<string>("MediaInstructionMediaContainerName")
                                        .HasColumnType("text");

                                    b2.Property<string>("MediaInstructionMediaBlobName")
                                        .HasColumnType("text");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<bool>("IsSquare")
                                        .HasColumnType("boolean");

                                    b2.Property<double>("Resolution")
                                        .HasColumnType("double precision");

                                    b2.HasKey("MediaInstructionMediaContainerName", "MediaInstructionMediaBlobName", "Id");

                                    b2.ToTable("ThumbnailInstruction");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaInstructionMediaContainerName", "MediaInstructionMediaBlobName");
                                });

                            b1.OwnsOne("Shared.Events.SharedObjects.TranscodingInstruction", "TranscodingInstruction", b2 =>
                                {
                                    b2.Property<string>("MediaInstructionMediaContainerName")
                                        .HasColumnType("text");

                                    b2.Property<string>("MediaInstructionMediaBlobName")
                                        .HasColumnType("text");

                                    b2.Property<double>("Resolution")
                                        .HasColumnType("double precision");

                                    b2.HasKey("MediaInstructionMediaContainerName", "MediaInstructionMediaBlobName");

                                    b2.ToTable("Media");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaInstructionMediaContainerName", "MediaInstructionMediaBlobName");
                                });

                            b1.Navigation("MetadataInstruction")
                                .IsRequired();

                            b1.Navigation("ModerationInstruction");

                            b1.Navigation("ThumbnailInstructions");

                            b1.Navigation("TranscodingInstruction");
                        });

                    b.OwnsOne("Shared.Events.SharedObjects.Metadata", "Metadata", b1 =>
                        {
                            b1.Property<string>("MediaContainerName")
                                .HasColumnType("text");

                            b1.Property<string>("MediaBlobName")
                                .HasColumnType("text");

                            b1.Property<double>("Duration")
                                .HasColumnType("double precision");

                            b1.Property<double>("Height")
                                .HasColumnType("double precision");

                            b1.Property<double>("Width")
                                .HasColumnType("double precision");

                            b1.HasKey("MediaContainerName", "MediaBlobName");

                            b1.ToTable("Media");

                            b1.WithOwner()
                                .HasForeignKey("MediaContainerName", "MediaBlobName");
                        });

                    b.OwnsOne("Shared.Events.SharedObjects.ModerationResult", "ModerationResult", b1 =>
                        {
                            b1.Property<string>("MediaContainerName")
                                .HasColumnType("text");

                            b1.Property<string>("MediaBlobName")
                                .HasColumnType("text");

                            b1.Property<int>("Hate")
                                .HasColumnType("integer");

                            b1.Property<int>("SelfHarm")
                                .HasColumnType("integer");

                            b1.Property<int>("Sexual")
                                .HasColumnType("integer");

                            b1.Property<int>("Violence")
                                .HasColumnType("integer");

                            b1.HasKey("MediaContainerName", "MediaBlobName");

                            b1.ToTable("Media");

                            b1.WithOwner()
                                .HasForeignKey("MediaContainerName", "MediaBlobName");
                        });

                    b.OwnsMany("Shared.Events.SharedObjects.Thumbnail", "Thumbnails", b1 =>
                        {
                            b1.Property<string>("MediaContainerName")
                                .HasColumnType("text");

                            b1.Property<string>("MediaBlobName")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("BlobName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("IsSquare")
                                .HasColumnType("boolean");

                            b1.Property<double>("Resolution")
                                .HasColumnType("double precision");

                            b1.HasKey("MediaContainerName", "MediaBlobName", "Id");

                            b1.ToTable("Thumbnail");

                            b1.WithOwner()
                                .HasForeignKey("MediaContainerName", "MediaBlobName");
                        });

                    b.Navigation("Instruction")
                        .IsRequired();

                    b.Navigation("Metadata");

                    b.Navigation("ModerationResult");

                    b.Navigation("Thumbnails");
                });
#pragma warning restore 612, 618
        }
    }
}
