// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudyProgramService.Infrastructure.PostgreSqlDb;

#nullable disable

namespace StudyProgramService.Infrastructure.Migrations
{
    [DbContext(typeof(PostgreSqlContext))]
    [Migration("20260220065553_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudyProgramService.Domain.Entities.SP", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("StudyPrograms");
                });

            modelBuilder.Entity("StudyProgramService.Domain.Entities.SP", b =>
                {
                    b.OwnsOne("StudyProgramService.Domain.ValueObjects.SPDailyStudyTarget", "DailyStudyTarget", b1 =>
                        {
                            b1.Property<Guid>("SPId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer");

                            b1.HasKey("SPId");

                            b1.ToTable("StudyPrograms");

                            b1.WithOwner()
                                .HasForeignKey("SPId");
                        });

                    b.OwnsOne("StudyProgramService.Domain.ValueObjects.SPDaysPerWeek", "DaysPerWeek", b1 =>
                        {
                            b1.Property<Guid>("SPId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer");

                            b1.HasKey("SPId");

                            b1.ToTable("StudyPrograms");

                            b1.WithOwner()
                                .HasForeignKey("SPId");
                        });

                    b.OwnsOne("StudyProgramService.Domain.ValueObjects.SPDescription", "Description", b1 =>
                        {
                            b1.Property<Guid>("SPId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("SPId");

                            b1.ToTable("StudyPrograms");

                            b1.WithOwner()
                                .HasForeignKey("SPId");
                        });

                    b.OwnsOne("StudyProgramService.Domain.ValueObjects.SPDurationInWeeks", "DurationInWeeks", b1 =>
                        {
                            b1.Property<Guid>("SPId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer");

                            b1.HasKey("SPId");

                            b1.ToTable("StudyPrograms");

                            b1.WithOwner()
                                .HasForeignKey("SPId");
                        });

                    b.OwnsOne("StudyProgramService.Domain.ValueObjects.SPEnrollmentStrategy", "EnrollmentStrategy", b1 =>
                        {
                            b1.Property<Guid>("SPId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("SPId");

                            b1.ToTable("StudyPrograms");

                            b1.WithOwner()
                                .HasForeignKey("SPId");
                        });

                    b.OwnsOne("StudyProgramService.Domain.ValueObjects.SPMoney", "Price", b1 =>
                        {
                            b1.Property<Guid>("SPId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric");

                            b1.HasKey("SPId");

                            b1.ToTable("StudyPrograms");

                            b1.WithOwner()
                                .HasForeignKey("SPId");

                            b1.OwnsOne("StudyProgramService.Domain.ValueObjects.SPCurrency", "Currency", b2 =>
                                {
                                    b2.Property<Guid>("SPMoneySPId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("SPMoneySPId");

                                    b2.ToTable("StudyPrograms");

                                    b2.WithOwner()
                                        .HasForeignKey("SPMoneySPId");
                                });

                            b1.Navigation("Currency")
                                .IsRequired();
                        });

                    b.OwnsOne("StudyProgramService.Domain.ValueObjects.SPTitle", "Title", b1 =>
                        {
                            b1.Property<Guid>("SPId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("SPId");

                            b1.ToTable("StudyPrograms");

                            b1.WithOwner()
                                .HasForeignKey("SPId");
                        });

                    b.Navigation("DailyStudyTarget")
                        .IsRequired();

                    b.Navigation("DaysPerWeek")
                        .IsRequired();

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("DurationInWeeks")
                        .IsRequired();

                    b.Navigation("EnrollmentStrategy")
                        .IsRequired();

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
