// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudyProgramInviteService.Infrastructure.PostgreSql;

#nullable disable

namespace StudyProgramInviteService.Infrastructure.Migrations
{
    [DbContext(typeof(SqlContext))]
    partial class SqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudyProgramInviteService.Domain.SPI", b =>
                {
                    b.Property<Guid>("StudyProgramId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("StudyProgramOwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("StudyProgramId", "UserId");

                    b.ToTable("StudyProgramInvites");
                });

            modelBuilder.Entity("StudyProgramInviteService.Domain.SPI", b =>
                {
                    b.OwnsMany("StudyProgramInviteService.Domain.SPIState", "States", b1 =>
                        {
                            b1.Property<Guid>("SPIStudyProgramId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("SPIUserId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int?>("InvalidationReason")
                                .HasColumnType("integer");

                            b1.Property<int>("StateValue")
                                .HasColumnType("integer");

                            b1.HasKey("SPIStudyProgramId", "SPIUserId", "Id");

                            b1.ToTable("StudyProgramInviteStates");

                            b1.WithOwner()
                                .HasForeignKey("SPIStudyProgramId", "SPIUserId");
                        });

                    b.Navigation("States");
                });
#pragma warning restore 612, 618
        }
    }
}
